# Generated by Django 4.2.1 on 2025-01-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0001_initial'),
    ]

    operations = []
