# Generated by Django 5.2.17 on 2026-09-12 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OpenBench", "0023_datasetupload_next_attempt_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingrun",
            name="completed_superbatches",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trainingrun",
            name="continuation_checkpoint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="continuing_runs",
                to="OpenBench.trainingcheckpoint",
            ),
        ),
        migrations.AddField(
            model_name="trainingrun",
            name="last_allocated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingrun",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trainingrun",
            name="workload_size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trainingworker",
            name="last_allocation_kind",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.CreateModel(
            name="TrainingWorkload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim_token", models.UUIDField(unique=True)),
                ("start", models.PositiveIntegerField()),
                ("end", models.PositiveIntegerField()),
                ("state", models.CharField(default="ACTIVE", max_length=16)),
                ("report_sequence", models.BigIntegerField(default=0)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                (
                    "checkpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workloads",
                        to="OpenBench.trainingcheckpoint",
                    ),
                ),
                (
                    "resume_checkpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resuming_workloads",
                        to="OpenBench.trainingcheckpoint",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workloads",
                        to="OpenBench.trainingrun",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workloads",
                        to="OpenBench.trainingworker",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trainingartifact",
            name="workload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artifacts",
                to="OpenBench.trainingworkload",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingworkload",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "ACTIVE")),
                fields=("run",),
                name="one_active_workload_per_run",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingworkload",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "ACTIVE")),
                fields=("worker",),
                name="one_active_workload_per_worker",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingworkload",
            constraint=models.CheckConstraint(
                condition=models.Q(("end__gte", models.F("start")), ("start__gte", 1)),
                name="valid_training_workload_bounds",
            ),
        ),
    ]
