# Generated by Django 5.2.17 on 2026-09-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OpenBench", "0024_training_workloads"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingworker",
            name="test_assignment",
            field=models.JSONField(default=dict),
        ),
    ]
