# Generated by Django 5.2.17 on 2026-09-12 13:57

import OpenBench.notification_events
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OpenBench", "0025_training_test_assignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="execution_number",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="DiscordConfiguration",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("webhook_ciphertext", models.TextField(blank=True)),
                ("generation", models.UUIDField(default=uuid.uuid4)),
                ("destination_label", models.CharField(blank=True, max_length=128)),
                ("guild_id", models.CharField(blank=True, max_length=20)),
                ("channel_id", models.CharField(blank=True, max_length=20)),
                ("canonical_url", models.URLField(blank=True)),
                ("sender_seen", models.DateTimeField(blank=True, null=True)),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                (
                    "next_send_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="discord_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("discord_user_id", models.CharField(blank=True, max_length=20)),
                (
                    "events",
                    models.JSONField(
                        default=OpenBench.notification_events.default_events
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_key", models.CharField(max_length=64)),
                ("subject_key", models.CharField(max_length=100)),
                ("generation", models.UUIDField()),
                ("summary", models.JSONField(default=dict)),
                ("ping_requested", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=16),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("claimed_until", models.DateTimeField(blank=True, null=True)),
                ("claim_token", models.UUIDField(blank=True, null=True)),
                ("message_id", models.CharField(blank=True, max_length=20)),
                ("last_error", models.CharField(blank=True, max_length=200)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OpenBench.lifecycleevent",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["subject_key", "id"], name="discord_subject_order"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "recipient"),
                        name="unique_discord_event_recipient",
                    )
                ],
            },
        ),
    ]
