"""
Django settings for OpenSite project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import json
import os

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('OPENBENCH_DEBUG', '1').lower() in ('1', 'true', 'yes')
SECRET_KEY = os.environ.get('OPENBENCH_SECRET_KEY', '')
if not SECRET_KEY and DEBUG:
    SECRET_KEY = 'development-only-openbench-key-never-use-this-for-production'
if not SECRET_KEY or not DEBUG and (len(SECRET_KEY) < 50 or len(set(SECRET_KEY)) < 5):
    raise ImproperlyConfigured('Set OPENBENCH_SECRET_KEY to a random secret of at least 50 characters.')

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('OPENBENCH_ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1]' if DEBUG else '').split(',') if host.strip()]
if not ALLOWED_HOSTS or not DEBUG and '*' in ALLOWED_HOSTS:
    raise ImproperlyConfigured('Set OPENBENCH_ALLOWED_HOSTS to the production hostnames.')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.environ.get('OPENBENCH_CSRF_ORIGINS', '').split(',') if origin.strip()]
if os.environ.get('OPENBENCH_TRUST_PROXY') == '1':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('OPENBENCH_HSTS_SUBDOMAINS') == '1'
SECURE_HSTS_PRELOAD = os.environ.get('OPENBENCH_HSTS_PRELOAD') == '1'
SECURE_CONTENT_TYPE_NOSNIFF = True

HTML_MINIFY   = True
APPEND_SLASH  = True

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Application definition

SETTINGS_DIR  = os.path.dirname(__file__)
PROJECT_PATH  = os.path.join(SETTINGS_DIR, os.pardir)
PROJECT_PATH  = os.path.abspath(PROJECT_PATH)
TEMPLATE_PATH = os.path.join(PROJECT_PATH, 'Templates')

MEDIA_URL  = '/Media/'
MEDIA_ROOT = os.environ.get('OPENBENCH_MEDIA_ROOT', os.path.join(BASE_DIR, 'Media'))

INSTALLED_APPS = [
    'daphne',
    'OpenBench',
    'OpenBench.templatetags',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'OpenBench.config.ConfigurationMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
]

ROOT_URLCONF = 'OpenSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'OpenSite.wsgi.application'
ASGI_APPLICATION = 'OpenSite.asgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

database_config_path = os.environ.get('OPENBENCH_DATABASE_CONFIG')
if database_config_path:
    with open(database_config_path, encoding='utf-8') as database_config_file:
        database_config = json.load(database_config_file)
    if not isinstance(database_config, dict) or not isinstance(database_config.get('ENGINE'), str) or not database_config['ENGINE']:
        raise ImproperlyConfigured('OPENBENCH_DATABASE_CONFIG must contain a Django database connection object with ENGINE.')
    DATABASES = {'default': database_config}
if not DEBUG and DATABASES['default']['ENGINE'] != 'django.db.backends.postgresql':
    raise ImproperlyConfigured('Production training requires PostgreSQL. Set OPENBENCH_DATABASE_CONFIG.')


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.environ.get('OPENBENCH_STATIC_ROOT', os.path.join(BASE_DIR, 'StaticFiles'))

TRAINING_ROOT = os.environ.get('MATTBENCH_TRAINING_ROOT', os.path.join(BASE_DIR, 'TrainingData'))
TRAINING_CREDENTIAL_KEY = os.environ.get('MATTBENCH_CREDENTIAL_KEY', '')
TRAINING_CREDENTIAL_KEY_FILE = os.environ.get('MATTBENCH_CREDENTIAL_KEY_FILE', '')
if DEBUG and not TRAINING_CREDENTIAL_KEY and not TRAINING_CREDENTIAL_KEY_FILE:
    TRAINING_CREDENTIAL_KEY_FILE = os.path.join(BASE_DIR, 'Deploy', 'credential.key')
TRAINING_WORKER_TIMEOUT = 600
TRAINING_VALIDATION_TIMEOUT = int(os.environ.get('MATTBENCH_VALIDATION_TIMEOUT', '600'))
TRAINING_UPLOAD_TIMEOUT = int(os.environ.get('MATTBENCH_UPLOAD_TIMEOUT', '86400'))
TRAINING_MAX_ARTIFACT_BYTES = 8 * 1024 ** 3
TRAINING_STORAGE_RESERVE_BYTES = int(os.environ.get('MATTBENCH_STORAGE_RESERVE_GB', '10')) * 1024 ** 3
TRAINING_REPLICA_ROOT = os.environ.get('MATTBENCH_REPLICA_ROOT', '')
if TRAINING_REPLICA_ROOT and os.path.realpath(TRAINING_REPLICA_ROOT) == os.path.realpath(TRAINING_ROOT):
    raise ImproperlyConfigured('Artifact replicas must use a separate storage root.')
if not DEBUG and (not TRAINING_CREDENTIAL_KEY_FILE or not TRAINING_REPLICA_ROOT):
    raise ImproperlyConfigured('Production training requires MATTBENCH_CREDENTIAL_KEY_FILE and MATTBENCH_REPLICA_ROOT on durable storage.')
LOGGING = {
    'version': 1, 'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'loggers': {'OpenBench.training_tasks': {'handlers': ['console'], 'level': 'INFO'}, 'OpenBench.training_storage': {'handlers': ['console'], 'level': 'INFO'}},
}
