const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const path = require('node:path');
(async () => {
    const server = spawn(path.resolve('bin/python'), ['Scripts/test_builder_browser.py']);
    const url = await new Promise((resolve, reject) => {
        server.stdout.once('data', data => resolve(data.toString().trim()));
        server.once('error', reject);
        server.stderr.on('data', data => process.stderr.write(data));
    });
    let browser;
    try {
        browser = await chromium.launch({headless: true, executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE});
        const page = await browser.newPage({viewport: {width: 1440, height: 1100}});
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        await page.route('https://**/*', route => route.abort());
        await page.goto(url);
        await page.waitForSelector('#builder-lr-stages [data-stage-field="length"]', {state: 'attached'});
        await page.click('#tab-training');
        await page.click('#builder-add-lr-stage');
        const lengths = page.locator('#builder-lr-stages [data-stage-field="length"]');
        await lengths.nth(0).fill('100'); await lengths.nth(1).fill('700');
        assert.deepEqual(await page.locator('#builder-lr-stages output').allTextContents(), ['SB 1–100', 'SB 101–800']);
        await page.selectOption('#builder-lr-mode', 'boundaries');
        assert.deepEqual(await page.locator('#builder-lr-stages [data-stage-field="end"]').evaluateAll(inputs => inputs.map(i => i.value)), ['100', '800']);
        await page.selectOption('#builder-lr-mode', 'lengths');
        await page.fill('[name="superbatches"]', '900');
        assert.match(await page.locator('#builder-lr-allocation').textContent(), /100 SB shortfall/);
        assert.deepEqual(await lengths.evaluateAll(inputs => inputs.map(i => i.value)), ['100', '700']);
        await page.selectOption('#builder-lr-mode', 'boundaries');
        assert.equal(await page.locator('#builder-lr-mode').inputValue(), 'lengths');
        await page.fill('[name="superbatches"]', '800');
        await lengths.nth(1).fill('');
        await page.selectOption('#builder-lr-mode', 'boundaries');
        assert.equal(await lengths.nth(1).inputValue(), '');
        await lengths.nth(1).fill('700');
        await page.click('#builder-lr-stages fieldset:first-child button');
        assert.equal(await lengths.nth(0).inputValue(), '800');
        await page.click('#tab-network');
        await page.click('#builder-assign-buckets');
        await page.locator('#builder-bucket-dialog summary').click();
        const imported = Array.from({length: 32}, (_, i) => Math.floor(i / 4));
        await page.fill('#builder-layout-import', '[' + imported.join(', ') + ',]');
        await page.selectOption('#builder-layout-order', 'a8');
        await page.click('#builder-import-layout');
        const square = i => page.locator('[data-square="' + i + '"]');
        assert.equal(await square(0).textContent(), '7');
        assert.equal(await square(56).textContent(), '0');
        await page.locator('#builder-bucket-dialog summary').click();
        await square(0).click();
        assert.equal(await square(0).textContent(), '0');
        assert.equal(await square(7).textContent(), '0');
        await square(0).click({button: 'right'});
        assert.equal(await square(0).textContent(), '7');
        await square(0).hover(); await page.mouse.wheel(0, -50);
        await page.waitForTimeout(50);
        assert.equal(await square(0).textContent(), '0');
        await page.click('#builder-undo-layout');
        assert.equal(await square(0).textContent(), '7');
        const src = await square(0).boundingBox(), dst = await square(8).boundingBox(), dst2 = await square(16).boundingBox();
        await page.mouse.move(src.x + 10, src.y + 10); await page.mouse.down();
        await page.mouse.move(dst.x + 10, dst.y + 10); await page.mouse.move(dst2.x + 10, dst2.y + 10); await page.mouse.up();
        assert.equal(await square(8).textContent(), '7'); assert.equal(await square(16).textContent(), '7');
        await page.click('#builder-undo-layout');
        assert.equal(await square(8).textContent(), '6'); assert.equal(await square(16).textContent(), '5');
        await page.click('#builder-flip-layout');
        assert.equal(await square(0).textContent(), '0');
        assert.match(await page.locator('#builder-board-convention').textContent(), /Indexing: a1=0/);
        await page.click('#builder-undo-layout');
        await page.click('#builder-close-buckets');
        await page.check('[name="pairwise_activation"]');
        assert.match(await page.locator('#builder-architecture').textContent(), /768\)x2-pw/);
        assert.equal((await page.locator('#builder-architecture').textContent()).match(/x2/g).length, 1);
        await page.click('#tab-training');
        await page.locator('summary').filter({hasText: 'Position filtering'}).click();
        assert.equal(await page.locator('#builder-piece-count-keep input').count(), 33);
        await page.check('[name="piece_count_sampling"]');
        await page.selectOption('[name="piece_count_mode"]', 'target');
        await page.locator('summary').filter({hasText: 'Import piece-count'}).click();
        const dist = [0, 0, ...Array(31).fill(1 / 31)];
        await page.fill('#builder-piece-import', JSON.stringify(dist));
        await page.click('#builder-import-pieces');
        await page.click('#builder-save');
        await page.waitForFunction(() => document.querySelector('#builder-feedback').textContent.startsWith('Saved'));
        await page.reload();
        assert.equal(await page.locator('[name="piece_count_mode"]').inputValue(), 'target');
        assert.deepEqual(await page.locator('#builder-piece-count-keep input').evaluateAll(inputs => inputs.map(i => Number(i.value))), dist);
        assert.deepEqual(errors, []);
        console.log('Browser imports, board gestures, undo, stage drafts, architecture and save/reload passed.');
    } finally { if (browser) await browser.close(); server.kill(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
